- name: Deploying war into Apache Tomcat
  hosts: tomcat
  become: true
  become_user: root
  vars: 
    tomcat_port: 8082
  
  tasks:
    - name: Deploy war file into tomcat server
      import_role:
        name: ansible-tomcat-roles
